function Hd = fir4000
%FIR4000 返回离散时间滤波器对象。

% MATLAB Code
% Generated by MATLAB(R) 9.12 and DSP System Toolbox 9.14.
% Generated on: 27-Nov-2022 21:23:46

% Equiripple Highpass filter designed using the FIRPM function.

% All frequency values are in Hz.
Fs = 8192;  % Sampling Frequency

Fstop = 2000;            % Stopband Frequency
Fpass = 2010;            % Passband Frequency
Dstop = 1e-05;           % Stopband Attenuation
Dpass = 0.057501127785;  % Passband Ripple
dens  = 20;              % Density Factor

% Calculate the order from the parameters using FIRPMORD.
[N, Fo, Ao, W] = firpmord([Fstop, Fpass]/(Fs/2), [0 1], [Dstop, Dpass]);

% Calculate the coefficients using the FIRPM function.
b  = firpm(N, Fo, Ao, W, {dens});
Hd = dfilt.dffir(b);

% [EOF]
