get
{
    list    sorted 
    list    raw           generated by splited.string
    string  splited       from raw.string
    string  raw           read form csv file
}



process
{
    list.sorted <===4 list.raw <===3 string splited <===2 string raw <===1 csv.file
}


make key
{
    key_1 of main value
    key_2 of vice value

}


step_1_2_3
{
    open the file wholely

    repalce the "," by " "

    .split
}


step_4
{
    clear: remove the Duplicates 
    {
        list ===> set 
        set  ===> list
        {
                    
            loop i in ("set")
            {
                add i to list
            
            }
        }
    }


    pack list into dict 


    output 
}












    use selection_sort 
    {
        loop("x = (n - 1)")
        {
            get_largest_so_far
            {
                loop("x")
                {
                    compare and store
                    ...
                    compare and store
                    ...
                    ....
                }

                "x = x - 1"
            }

            ...

            get_largest_so_far
            {
                loop("x")
                {
                    compare and store
                    ...
                    compare and store
                    ...
                    ....
                }
                "x = x - 1"
            }

            ...

            ....
        }
    }

 
